import { Metadata } from "next";
import { Inter } from "next/font/google";

export const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Drain Store",
  description: "Generated by create next app",
};
