import "./globals.css";
import AppShell from "@/components/fragments/AppShell";
import { Metadata } from "next";
import { Inter } from "next/font/google";

export const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Drain Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-100`}>
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
